# Generated by Django 3.2.9 on 2022-02-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='pics')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('bool', models.BooleanField(default=False)),
            ],
        ),
    ]
