# Generated by Django 3.2.9 on 2022-02-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinations',
            old_name='bool',
            new_name='offer',
        ),
        migrations.AlterField(
            model_name='destinations',
            name='image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
