# Generated by Django 3.2.9 on 2022-02-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_auto_20220208_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
